services:
  - type: web
    name: fastapi-draw-server
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn server_qr:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: RENDER_EXTERNAL_URL
        value: "https://draw-wall0-5.onrender.com/"

